graph TD
  sessions[sessions]
  news[news]
  tasks[tasks]
  user_verifications[user_verifications]
  attendances[attendances]
  employee_offices[employee_offices]
  cache[cache]
  offices[offices]
  users[users]
